<div class="aboutpage ">

<?php include('header.php'); ?>
<div class=" blogPage">

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h1 style="margin-bottom: 30px;">Terms and Conditions</h1>
      <p style="text-align: justify; margin-bottom: 30px;">Please read the terms and conditions carefully in the event of acceptance, the user is deemed to have assented to all the conditions that have been subscribed by the service provider or by their agents or assessors and aides the term wherever shall include but not limited to the aforementioned and the expression in no terms may be treated to deem an exhaustive list wherein the service provider is free to enter more clauses into the already mentioned clauses by insertion of an addendum to the existing terms and conditions.</p>
      <ul style="list-style-position: inside; padding-left: 0; margin: 0;">
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the acceptance of the terms and conditions is the user’s willful intention to commit to all of the conditions set forth by the provider and at no point can the user be deemed to not having assented to a particular term and once the user adheres to the terms it is therefore deemed fit that the user has assented to every term.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the material available on the portal is the sole property of the provider and the provider has the sole discretion in deciphering which material to levy a charge for and which materials will be provided without an additional charge. By signing up on the portal the user understands that its data would be shared by the provider with its partners which will include but not limit to its partners and other platforms where ever it is deemed necessary by the user in similar areas such as the portal which has been signed up for.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That access to the portal is for one user per login/ID and counterfeiting of the material is strictly prohibited.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the user has deemed to have understood that by signing up they are treated as a student of the particular portal and specifically of the material that they are accessing at the given point in time and in no way can they act as an assessor?</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the provider does not have any agency /principal relationship with the user.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the service provider is in no way responsible for the performance of the user/student in the exams that the user wishes to take or is studying for as this is a platform that provides mere guidance and is not an assessment body where the performance of the user can be assessed or is benchmarked against any accredited boards or universities.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the provider is within the geographical limits of Pakistan and hence the territorial limits of Pakistan shall form the jurisdiction of courts of competent jurisdiction in Pakistan.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the user has signed is deemed to have accepted the portal as an ancillary body to formal education and in form is the provider asserting the portal as a
      substitute to the formal channels of education and hence, not a body to provide a measure on the user’s progress.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the user has attended sessions on the portals is no measure of the academic performance of the user and the provider is in no way or form responsible for the performance of the user in any competitive examination.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That if a user is under the legal consenting age which is eighteen years in Pakistan it is deemed that the access has been provided through the supervision of a parent/guardian and the terms have not only been understood by the user but in this case have been understood by the supervisor of the user.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the user has no right to challenge the method of teaching of a particular instructor and how an instructor conducts the sessions is the sole discretion of the instructor.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the students can request a full refund within 2 days of purchase if they have not started the course. The request must be made through our official contact channels.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the refund requests made after the course has begun, but within 7 days are eligible for a partial refund. The partial refund amount will be determined based on the course’s progress.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the refund is only available to the user who has not been suspended due to a violation of any of the terms and conditions or any disciplinary action has not been taken against them by the provider.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> If there is any breach in the terms and conditions or any other disciplinary breach that may take place on part of the user the provider has the sole discretion to suspend/terminate the user from the portal with immediate effect without any prior notice/warning in the event of a serious breach.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the constitution of a serious breach is the sole discretion of the provider and the user has no right to question the provider’s criterion.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the data of other users and the privacy of all the users are paramount to the provider and any attempt to tamper with the cyber security of the portal will be deemed a criminal offence as envisaged in the Cyber Crimes Act 2020.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> If the user’s stipulated period is ending and the user wishes to access the material of the provider, the user must pay the continuing stipulation or join one of the crash courses to obtain continual access.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> If a user indulges in the practice of sharing any banned content or content not fit for the purpose, the provider has a zero-tolerance policy and the violators shall be suspended from the forum immediately.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> In the event of any spamming by the user, the provider would by way of a unilateral action terminate the account of the user without allowing the user to re-enter under any circumstance.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> That the terms envisaged above are in countenance with the laws governing the fair usage policy and aim to protect the rights and privileges of all involved.</li></br>
      <li style="text-align: justify; margin-bottom: 10px; position: relative; padding-left: 20px;"><span style="position: absolute; left: 0; top: 0;">•</span> To ensure security and a seamless learning experience, Orb-Ed has a device restriction policy. You will be able to access your Orb-Ed account on ANY ONE device. Device switching is not allowed as the first device used to access your account will be considered as your permanent device.</li></br>
      <ul>
    </div>
  </div>
</div>

</div>

<?php include('footer.php'); ?>
</div>